#include "cooperative_transportation_4ws_backstepping/kinematics_solver.hpp"
#include "cooperative_transportation_4ws_backstepping/initial.hpp"
#include "cooperative_transportation_4ws_backstepping/mathFunc.h"
#include <array>
#include <iostream>

double KinematicsSolver::calc_aqd_17_()
{
double ret;
ret = (nu1(t)*(-(Sin(phi1(t) - thetap0(t) + thetap1(t))*Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))) + Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t))) - (Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)) + Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t))))*Tan(phi4(t))))/RADIUS + (uact1(t)*(-(Power(Sec(phi4(t)),2)*(Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)) + Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t))))*uact6(t)) - Cos(phi1(t) - thetap0(t) + thetap1(t))*Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(-uact2(t) + uact3(t) + Derivative(1)(thetap1)(t)) + Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(2*Power(Sec(phi1(t)),2)*Sin(phi1(t) - thetap0(t) + thetap1(t))*uact3(t) - Sin(phi1(t) - thetap0(t) + thetap1(t))*(-uact2(t) + uact3(t) + Derivative(1)(thetap1)(t)) + 2*Cos(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t))*(-uact2(t) + uact3(t) + Derivative(1)(thetap1)(t))) - Tan(phi4(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t))*Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(-uact2(t) + uact3(t) + Derivative(1)(thetap1)(t)) + Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(2*Power(Sec(phi1(t)),2)*Sin(phi1(t) - thetap0(t) + thetap1(t))*uact3(t) - Sin(phi1(t) - thetap0(t) + thetap1(t))*(-uact2(t) + uact3(t) + Derivative(1)(thetap1)(t)) + 2*Cos(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t))*(-uact2(t) + uact3(t) + Derivative(1)(thetap1)(t))) - Sin(phi1(t) - thetap0(t) + thetap1(t))*Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(uact3(t) - uact4(t) + Derivative(1)(thetap1)(t) - Derivative(1)(thetap2)(t)) + Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t)))*(uact3(t) - uact4(t) + Derivative(1)(thetap1)(t) - Derivative(1)(thetap2)(t))) - Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*Sin(phi1(t) - thetap0(t) + thetap1(t))*(uact3(t) - uact4(t) + Derivative(1)(thetap1)(t) - Derivative(1)(thetap2)(t)) - Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t)))*(uact3(t) - uact4(t) + Derivative(1)(thetap1)(t) - Derivative(1)(thetap2)(t))))/RADIUS;
return ret;
}
