#include "cooperative_transportation_4ws_backstepping/kinematics_solver.hpp"
#include "cooperative_transportation_4ws_backstepping/initial.hpp"
#include "cooperative_transportation_4ws_backstepping/mathFunc.h"
#include <array>
#include <iostream>

double KinematicsSolver::calc_d_SX_d_t_7_1_()
{
double ret;
ret = (c(s(t))*(u2 - (u1*c(s(t))*Cos(thetap0(t)))/(1 - c(s(t))*d(t)))*Sin(thetap0(t)))/(1 - c(s(t))*d(t)) + (Sec(phi2(t))*(-(Cos(phi1(t) - thetap0(t) + thetap1(t))*Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(-u2 + u3 + (u1*c(s(t))*Cos(thetap0(t)))/(1 - c(s(t))*d(t)) + u1*(-((c(s(t))*Cos(thetap0(t)))/(1 - c(s(t))*d(t))) + (Sec(phi1(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)))/l1))) - Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(2*u3*Power(Sec(phi1(t)),2)*Sin(phi1(t) - thetap0(t) + thetap1(t)) - Sin(phi1(t) - thetap0(t) + thetap1(t))*(-u2 + u3 + (u1*c(s(t))*Cos(thetap0(t)))/(1 - c(s(t))*d(t)) + u1*(-((c(s(t))*Cos(thetap0(t)))/(1 - c(s(t))*d(t))) + (Sec(phi1(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)))/l1)) + 2*Cos(phi1(t) - thetap0(t) + thetap1(t))*(-u2 + u3 + (u1*c(s(t))*Cos(thetap0(t)))/(1 - c(s(t))*d(t)) + u1*(-((c(s(t))*Cos(thetap0(t)))/(1 - c(s(t))*d(t))) + (Sec(phi1(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)))/l1))*Tan(phi1(t))) + Sin(phi1(t) - thetap0(t) + thetap1(t))*Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(u3 - u4 + u1*(-((c(s(t))*Cos(thetap0(t)))/(1 - c(s(t))*d(t))) + (Sec(phi1(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)))/l1) - u1*(-((c(s(t))*Cos(thetap0(t)))/(1 - c(s(t))*d(t))) + (Sec(phi2(t))*(-(Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*Sin(phi1(t) - thetap0(t) + thetap1(t))) - Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t)))))/l2)) - Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t)))*(u3 - u4 + u1*(-((c(s(t))*Cos(thetap0(t)))/(1 - c(s(t))*d(t))) + (Sec(phi1(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)))/l1) - u1*(-((c(s(t))*Cos(thetap0(t)))/(1 - c(s(t))*d(t))) + (Sec(phi2(t))*(-(Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*Sin(phi1(t) - thetap0(t) + thetap1(t))) - Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t)))))/l2))))/l2 + (u4*Sec(phi2(t))*(-(Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*Sin(phi1(t) - thetap0(t) + thetap1(t))) - Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t))))*Tan(phi2(t)))/l2 - (Power(Cos(thetap0(t)),2)*uact1(t)*Derivative(1)(c)(s(t)))/Power(1 - c(s(t))*d(t),2) + (c(s(t))*Cos(thetap0(t))*(-(c(s(t))*Sin(thetap0(t))*uact1(t)) - (Cos(thetap0(t))*d(t)*uact1(t)*Derivative(1)(c)(s(t)))/(1 - c(s(t))*d(t))))/Power(1 - c(s(t))*d(t),2);
return ret;
}
