#include "cooperative_transportation_4ws_backstepping/kinematics_solver.hpp"
#include "cooperative_transportation_4ws_backstepping/initial.hpp"
#include "cooperative_transportation_4ws_backstepping/mathFunc.h"
#include <array>
#include <iostream>

double KinematicsSolver::calc_pd_alpha4_pd_X_1_7_()
{
double ret;
ret = (Power(1 - c(s(t))*d(t),2)*Power(Sec(phi2(t)),2)*Power(Sec(thetap0(t)),2)*Power(-(Sin(phi1(t) - thetap0(t) + thetap1(t))*Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))) + Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t))),2))/Power(l2,2) + (Power(1 - c(s(t))*d(t),2)*Sec(phi2(t))*Power(Sec(thetap0(t)),2)*(-((c(s(t))*Cos(thetap0(t)))/(1 - c(s(t))*d(t))) + (Sec(phi1(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)))/l1)*(-(Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*Sin(phi1(t) - thetap0(t) + thetap1(t))) - Cos(phi1(t) - thetap0(t) + thetap1(t))*Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t)) + Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(-Sin(phi1(t) - thetap0(t) + thetap1(t)) + 2*Cos(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t))) - Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t)))))/l2 + (Power(1 - c(s(t))*d(t),2)*Sec(phi2(t))*Power(Sec(thetap0(t)),2)*(Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)) + Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t))))*(-((c(s(t))*Cos(thetap0(t)))/(1 - c(s(t))*d(t))) + (Sec(phi2(t))*(-(Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*Sin(phi1(t) - thetap0(t) + thetap1(t))) - Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t)))))/l2))/l2 - (c(s(t))*(1 - c(s(t))*d(t))*Sec(phi2(t))*Sec(thetap0(t))*(-(Sin(phi1(t) - thetap0(t) + thetap1(t))*Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))) + Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t))))*Tan(thetap0(t)))/l2 - c(s(t))*(((1 - c(s(t))*d(t))*Sec(phi2(t))*Sec(thetap0(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t))*Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t)) + Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Sin(phi1(t) - thetap0(t) + thetap1(t)) - 2*Cos(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t)))))/l2 + ((1 - c(s(t))*d(t))*Sec(phi2(t))*Sec(thetap0(t))*(-(Sin(phi1(t) - thetap0(t) + thetap1(t))*Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))) + Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t))))*Tan(thetap0(t)))/l2) - (d(t)*Sec(phi2(t))*Sec(thetap0(t))*(-(Sin(phi1(t) - thetap0(t) + thetap1(t))*Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))) + Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t))))*Derivative(1)(c)(s(t)))/l2;
return ret;
}
