#include "cooperative_transportation_4ws_backstepping/kinematics_solver.hpp"
#include "cooperative_transportation_4ws_backstepping/initial.hpp"
#include "cooperative_transportation_4ws_backstepping/mathFunc.h"
#include <array>
#include <iostream>

double KinematicsSolver::calc_thetap2d_2_1_()
{
double ret;
ret = -(l3*Power(lv + 2*l3*Cos(thetap3(t) - thetap4d(t)),2)*Sin(thetap3(t) - thetap4d(t))*(w1*(1 - c(s(t))*d(t))*Sec(thetap0(t))*(-((c(s(t))*Cos(thetap0(t)))/(1 - c(s(t))*d(t))) + ((Cos(phi2(t) + thetap2(t) - thetap3(t)) + Sin(phi3(t))*Sin(phi2(t) - phi3(t) + thetap2(t) - thetap3(t)))*(Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)) + Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t)))) + (Cos(phi2(t) - phi3(t) + thetap2(t) - thetap3(t))*Sin(phi3(t)) - Sin(phi2(t) + thetap2(t) - thetap3(t)))*(-(Sin(phi1(t) - thetap0(t) + thetap1(t))*Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))) + Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t))) - 2*(Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)) + Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t))))*Tan(phi2(t))))/l3) - Derivative(1)(thetap4d)(t)))/(2.*Power(l2,3)*Sqrt(1 - Power(lv + 2*l3*Cos(thetap3(t) - thetap4d(t)),2)/(16.*Power(l2,2)))*(Power(lv + 2*l3*Cos(thetap3(t) - thetap4d(t)),2)/Power(l2,2) + 16*(1 - Power(lv + 2*l3*Cos(thetap3(t) - thetap4d(t)),2)/(16.*Power(l2,2))))) - (8*l3*Sqrt(1 - Power(lv + 2*l3*Cos(thetap3(t) - thetap4d(t)),2)/(16.*Power(l2,2)))*Sin(thetap3(t) - thetap4d(t))*(w1*(1 - c(s(t))*d(t))*Sec(thetap0(t))*(-((c(s(t))*Cos(thetap0(t)))/(1 - c(s(t))*d(t))) + ((Cos(phi2(t) + thetap2(t) - thetap3(t)) + Sin(phi3(t))*Sin(phi2(t) - phi3(t) + thetap2(t) - thetap3(t)))*(Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)) + Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t)))) + (Cos(phi2(t) - phi3(t) + thetap2(t) - thetap3(t))*Sin(phi3(t)) - Sin(phi2(t) + thetap2(t) - thetap3(t)))*(-(Sin(phi1(t) - thetap0(t) + thetap1(t))*Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))) + Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t))) - 2*(Cos(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)) + Sin(phi1(t) - phi2(t) + thetap1(t) - thetap2(t))*(Cos(phi1(t) - thetap0(t) + thetap1(t)) + 2*Sin(phi1(t) - thetap0(t) + thetap1(t))*Tan(phi1(t))))*Tan(phi2(t))))/l3) - Derivative(1)(thetap4d)(t)))/(l2*(Power(lv + 2*l3*Cos(thetap3(t) - thetap4d(t)),2)/Power(l2,2) + 16*(1 - Power(lv + 2*l3*Cos(thetap3(t) - thetap4d(t)),2)/(16.*Power(l2,2))))) + Derivative(1)(thetap4d)(t);
return ret;
}
