#include "cooperative_transportation_4ws_backstepping/kinematics_solver.hpp"
#include "cooperative_transportation_4ws_backstepping/initial.hpp"
#include "cooperative_transportation_4ws_backstepping/mathFunc.h"
#include <array>
#include <iostream>

double KinematicsSolver::calc_thetap8d_2_1_()
{
double ret;
ret = Derivative(1)(uthetap10d)(t) + (l3*Cos(Pi/6. - thetap9(t) + uthetap10d(t))*Power(lv + 2*l3*Sin(Pi/6. - thetap9(t) + uthetap10d(t)),2)*(-(w1*(1 - c(s(t))*d(t))*Sec(thetap0(t))*(-((c(s(t))*Cos(thetap0(t)))/(1 - c(s(t))*d(t))) + (Sec(phi9(t))*(-(Cos(phi8(t) - phi9(t) + thetap8(t) - thetap9(t))*(-2*Cos(phi8(t) - thetap0(t) + thetap8(t))*Sec(phi1(t))*Sin(Pi/6. + thetap0(t) - thetap1(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)) - (1 + 2*Cos(Pi/6. + thetap0(t) - thetap1(t))*Sec(phi1(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)))*Sin(phi8(t) - thetap0(t) + thetap8(t)))) + Sin(phi8(t) - phi9(t) + thetap8(t) - thetap9(t))*(Cos(phi8(t) - thetap0(t) + thetap8(t))*(1 + 2*Cos(Pi/6. + thetap0(t) - thetap1(t))*Sec(phi1(t))*Sin(phi1(t) - thetap0(t) + thetap1(t))) - 2*Sec(phi1(t))*Sin(Pi/6. + thetap0(t) - thetap1(t))*Sin(phi1(t) - thetap0(t) + thetap1(t))*Sin(phi8(t) - thetap0(t) + thetap8(t)) - 2*(-2*Cos(phi8(t) - thetap0(t) + thetap8(t))*Sec(phi1(t))*Sin(Pi/6. + thetap0(t) - thetap1(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)) - (1 + 2*Cos(Pi/6. + thetap0(t) - thetap1(t))*Sec(phi1(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)))*Sin(phi8(t) - thetap0(t) + thetap8(t)))*Tan(phi8(t)))))/l3)) + Derivative(1)(uthetap10d)(t)))/(2.*Power(l2,3)*Sqrt(1 - Power(lv + 2*l3*Sin(Pi/6. - thetap9(t) + uthetap10d(t)),2)/(16.*Power(l2,2)))*(Power(lv + 2*l3*Sin(Pi/6. - thetap9(t) + uthetap10d(t)),2)/Power(l2,2) + 16*(1 - Power(lv + 2*l3*Sin(Pi/6. - thetap9(t) + uthetap10d(t)),2)/(16.*Power(l2,2))))) + (8*l3*Cos(Pi/6. - thetap9(t) + uthetap10d(t))*Sqrt(1 - Power(lv + 2*l3*Sin(Pi/6. - thetap9(t) + uthetap10d(t)),2)/(16.*Power(l2,2)))*(-(w1*(1 - c(s(t))*d(t))*Sec(thetap0(t))*(-((c(s(t))*Cos(thetap0(t)))/(1 - c(s(t))*d(t))) + (Sec(phi9(t))*(-(Cos(phi8(t) - phi9(t) + thetap8(t) - thetap9(t))*(-2*Cos(phi8(t) - thetap0(t) + thetap8(t))*Sec(phi1(t))*Sin(Pi/6. + thetap0(t) - thetap1(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)) - (1 + 2*Cos(Pi/6. + thetap0(t) - thetap1(t))*Sec(phi1(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)))*Sin(phi8(t) - thetap0(t) + thetap8(t)))) + Sin(phi8(t) - phi9(t) + thetap8(t) - thetap9(t))*(Cos(phi8(t) - thetap0(t) + thetap8(t))*(1 + 2*Cos(Pi/6. + thetap0(t) - thetap1(t))*Sec(phi1(t))*Sin(phi1(t) - thetap0(t) + thetap1(t))) - 2*Sec(phi1(t))*Sin(Pi/6. + thetap0(t) - thetap1(t))*Sin(phi1(t) - thetap0(t) + thetap1(t))*Sin(phi8(t) - thetap0(t) + thetap8(t)) - 2*(-2*Cos(phi8(t) - thetap0(t) + thetap8(t))*Sec(phi1(t))*Sin(Pi/6. + thetap0(t) - thetap1(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)) - (1 + 2*Cos(Pi/6. + thetap0(t) - thetap1(t))*Sec(phi1(t))*Sin(phi1(t) - thetap0(t) + thetap1(t)))*Sin(phi8(t) - thetap0(t) + thetap8(t)))*Tan(phi8(t)))))/l3)) + Derivative(1)(uthetap10d)(t)))/(l2*(Power(lv + 2*l3*Sin(Pi/6. - thetap9(t) + uthetap10d(t)),2)/Power(l2,2) + 16*(1 - Power(lv + 2*l3*Sin(Pi/6. - thetap9(t) + uthetap10d(t)),2)/(16.*Power(l2,2)))));
return ret;
}
